name: "nether pathfinder mod windows"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v2.3.4
      - run: git submodule update --init --recursive
      - run: ./gradlew.bat build
      - name: Upload the built artifact
        uses: actions/upload-artifact@v2
        with:
          name: nether-pathfinder-mod-1.0.jar
          path: build/libs/nether-pathfinder-mod-1.0.jar
          if-no-files-found: error