name: "nether pathfinder mod windows"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v2.3.4
      - run: git submodule update --init --recursive
      - run: ./gradlew.bat build

      - name: Rename built mod
        run: move build\libs\nether-pathfinder-*.jar nether-pathfinder-${{ github.run_number }}.jar

      - name: Upload the built artifact
        uses: actions/upload-artifact@v2
        with:
          name: nether-pathfinder-${{ github.run_number }}
          path: nether-pathfinder-${{ github.run_number }}.jar
          if-no-files-found: error

      - name: Release Artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Latest Release - ${{ github.run_number }}"
          files: nether-pathfinder-*.jar